# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LLAdapterSwiftDemo' do
  use_frameworks!
      pod 'SnapKit', '5.0.0'
      pod 'LLAdapterSwift', :path => '../../LLAdapterSwift.podspec'
end
